### ISSUE TITLE
Add label for="" for spin button

### ISSUE THREAD

**Issue by epicfaace** [epicfaace/react-jsonschema-form#24]
### Prerequisites

- [ ] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

#### Expected behavior

[What you expected to happen]

#### Actual behavior

[What actually happened]

### Version

You can usually get this information in your `package.json` or in the file URL if you're using the unpkg one.

**Comment by sramaswami11** [comment]
Label already exists:
![image](https://user-images.githubusercontent.com/30377024/83984761-a4ea4000-a904-11ea-9cf1-8f04271b6a66.png)

**Comment by epicfaace** [comment]
@sramaswami11 we need to add the `for=""` attribute

**Comment by sramaswami11** [comment]
Done.

**Comment by epicfaace** [comment]
@sramaswami11 which PR?
